import customtkinter as ctk
from customtkinter import *
root=ctk.CTk()
root.title("Test")
root.state('zoomed')
ctk.set_appearance_mode("dark")
ctk.set_default_color_theme("green")
fre=CTkFrame(root,width=400,height=200)
fre.pack_propagate(False)
fre.place(relx=0.5,rely=0.3,anchor='center')
fr=CTkFrame(fre,width=400,height=200,fg_color="transparent")
fr.pack(pady=20)
def phno():
     a=e1.get()
     b=e2.get()
     print(a,b)
def destroy():
     root.destroy()
 
l1=CTkLabel(fr,text="phone number:")
l1.grid(column=0,row=0,padx=5,pady=5,sticky='es')
l2=CTkLabel(fr,text="password:")
l2.grid(column=0,row=1,padx=5,pady=5,sticky='wn')
e1=CTkEntry(fr)
e1.grid(column=1,row=0,columnspan=2,padx=5,pady=5,sticky='wse')
e2=CTkEntry(fr,show='*')
e2.grid(column=1,row=1,columnspan=2,padx=5,pady=5,sticky='wne')
b1=CTkButton(fr,text="submit",command=phno).grid(column=1,row=2,sticky='n')
b2=CTkButton(fr,text="cancel",command=destroy).grid(column=2,row=2,sticky='wn')
root.mainloop()